### ISSUE TITLE
summarize_barcode_summary script can fail when `barcode_front_total_trimmed` key missing

### ISSUE THREAD

**Issue by dfornika** [BCCDC-PHL/demultiplex-nanopore#1]
```
Traceback (most recent call last):
    File "summarize_barcoding_summary.py", line 90, in <module>
      main(args)
    File "summarize_barcoding_summary.py", line 54, in main
      for row in parse_barcode_summary(args.barcode_summary):
    File "summarize_barcoding_summary.py", line 43, in parse_barcode_summary
      row[field] = int(row[field])
                       ~~~^^^^^^^
  KeyError: 'barcode_front_total_trimmed'
```

**Comment by dfornika** [comment]
This appears to be related to the version of `guppy_barcoder` installed. This error appears with ont-guppy-cpu v6.5.7 but not with ont-guppy-cpu v6.3.7. I'll add a compatibility notice on the README.
